# Generated by Django 2.2.6 on 2020-01-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0003_auto_20200128_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
